version: '3.8'

services:
  app:
    image: abdulaziz111/my-app:latest
    container_name: myapp
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    restart: always
    networks:
      - app-network
    command: ['node', 'dist/main.js']

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
