services:
  postgres:
    image: postgres
    container_name: auth-app-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    networks:
      - auth_network
    ports:
      - '5436:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    container_name: auth-app
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - auth_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    restart: unless-stopped
    command: npm run start

networks:
  auth_network:

volumes:
  db_data:
